name: Deploy Flask & Vanilla Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.AWS_USERNAME }}/flask-app
            git pull origin main

            source venv/bin/activate
            pip install --upgrade pip
            pip install -r backend/requirements.txt

            sudo systemctl restart flask-app
            sudo cp -r frontend/* /var/www/html/

            echo " Deployment successful!"
